/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitcode;

/**
 *
 * @author vzako
 */
public class HealthRoutines extends javax.swing.JFrame {
    
    User user;
    
    /**
     * Creates new form HealthRoutines
     */
    public HealthRoutines(User user) {
        initComponents();
        this.user=user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        A7CB = new javax.swing.JCheckBox();
        AguaPGB = new javax.swing.JProgressBar();
        NameLabel = new javax.swing.JLabel();
        A1CB = new javax.swing.JCheckBox();
        A2CB = new javax.swing.JCheckBox();
        A3CB = new javax.swing.JCheckBox();
        A6CB = new javax.swing.JCheckBox();
        A5CB = new javax.swing.JCheckBox();
        A4CB = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BackToMenuBTN = new javax.swing.JButton();

        setTitle("Controle de líquido");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(226, 249, 206));
        jPanel3.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel6.setText("Controle de ingestão de água diário");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 20, 590, 55);

        A7CB.setBackground(new java.awt.Color(226, 249, 206));
        A7CB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A7CB.setText("19:00 / 300ml");
        A7CB.setFocusPainted(false);
        A7CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7CBActionPerformed(evt);
            }
        });
        jPanel3.add(A7CB);
        A7CB.setBounds(350, 510, 170, 70);
        jPanel3.add(AguaPGB);
        AguaPGB.setBounds(126, 150, 600, 40);

        NameLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        NameLabel.setText("2 L");
        jPanel3.add(NameLabel);
        NameLabel.setBounds(740, 140, 80, 55);

        A1CB.setBackground(new java.awt.Color(226, 249, 206));
        A1CB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A1CB.setText("7:00 / 300ml");
        A1CB.setFocusPainted(false);
        A1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1CBActionPerformed(evt);
            }
        });
        jPanel3.add(A1CB);
        A1CB.setBounds(80, 270, 170, 70);

        A2CB.setBackground(new java.awt.Color(226, 249, 206));
        A2CB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A2CB.setText("9:00 / 300ml");
        A2CB.setFocusPainted(false);
        A2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2CBActionPerformed(evt);
            }
        });
        jPanel3.add(A2CB);
        A2CB.setBounds(350, 270, 170, 70);

        A3CB.setBackground(new java.awt.Color(226, 249, 206));
        A3CB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A3CB.setText("11:00 / 300ml");
        A3CB.setFocusPainted(false);
        A3CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3CBActionPerformed(evt);
            }
        });
        jPanel3.add(A3CB);
        A3CB.setBounds(620, 270, 170, 70);

        A6CB.setBackground(new java.awt.Color(226, 249, 206));
        A6CB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A6CB.setText("17:00 / 300ml");
        A6CB.setFocusPainted(false);
        A6CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6CBActionPerformed(evt);
            }
        });
        jPanel3.add(A6CB);
        A6CB.setBounds(620, 390, 170, 70);

        A5CB.setBackground(new java.awt.Color(226, 249, 206));
        A5CB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A5CB.setText("15:00 / 300ml");
        A5CB.setFocusPainted(false);
        A5CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5CBActionPerformed(evt);
            }
        });
        jPanel3.add(A5CB);
        A5CB.setBounds(350, 390, 170, 70);

        A4CB.setBackground(new java.awt.Color(226, 249, 206));
        A4CB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        A4CB.setText("13:00 / 300ml");
        A4CB.setFocusPainted(false);
        A4CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4CBActionPerformed(evt);
            }
        });
        jPanel3.add(A4CB);
        A4CB.setBounds(80, 390, 170, 70);

        jPanel2.setBackground(new java.awt.Color(48, 165, 88));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fit");

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel2.setText("Code");

        BackToMenuBTN.setBackground(new java.awt.Color(226, 249, 206));
        BackToMenuBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackToMenuBTN.setText("< Voltar");
        BackToMenuBTN.setFocusPainted(false);
        BackToMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BackToMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(337, 337, 337))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BackToMenuBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuBTNActionPerformed
        // TODO add your handling code here:
        new MainMenu(this.user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackToMenuBTNActionPerformed

    private void A7CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A7CBActionPerformed

    private void A1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1CBActionPerformed

    private void A2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2CBActionPerformed

    private void A3CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3CBActionPerformed

    private void A6CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A6CBActionPerformed

    private void A5CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A5CBActionPerformed

    private void A4CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4CBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthRoutines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthRoutines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthRoutines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthRoutines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthRoutines(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A1CB;
    private javax.swing.JCheckBox A2CB;
    private javax.swing.JCheckBox A3CB;
    private javax.swing.JCheckBox A4CB;
    private javax.swing.JCheckBox A5CB;
    private javax.swing.JCheckBox A6CB;
    private javax.swing.JCheckBox A7CB;
    private javax.swing.JProgressBar AguaPGB;
    private javax.swing.JButton BackToMenuBTN;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
