/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fitcode;

/**
 *
 * @author vzako
 */

public class Trainings extends javax.swing.JFrame {

    User user;
    
    /**
     * Creates new form Trainings
     */
    public Trainings(User user) {
        initComponents();
        this.user=user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BackToMenuBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TobsesoBTN = new javax.swing.JButton();
        TabaixopesoBTN = new javax.swing.JButton();
        TnormalBTN = new javax.swing.JButton();
        TacimapesoBTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setTitle("Treinos");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowOnClose(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(48, 165, 88));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fit");

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel2.setText("Code");

        BackToMenuBTN.setBackground(new java.awt.Color(226, 249, 206));
        BackToMenuBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackToMenuBTN.setText("< Voltar");
        BackToMenuBTN.setFocusPainted(false);
        BackToMenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BackToMenuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(337, 337, 337))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BackToMenuBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(226, 249, 206));
        jPanel3.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel4.setText("Obesidade");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(570, 370, 260, 55);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel5.setText("Treinos diários");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 0, 260, 55);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel6.setText("Abaixo do peso");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(110, 70, 270, 55);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel7.setText("Normal");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(590, 70, 190, 55);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel8.setText("Acima do peso");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(110, 370, 290, 55);

        TobsesoBTN.setBackground(new java.awt.Color(48, 165, 88));
        TobsesoBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TobsesoBTN.setText("Ver treinos");
        TobsesoBTN.setFocusPainted(false);
        TobsesoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TobsesoBTNActionPerformed(evt);
            }
        });
        jPanel3.add(TobsesoBTN);
        TobsesoBTN.setBounds(570, 470, 150, 60);

        TabaixopesoBTN.setBackground(new java.awt.Color(48, 165, 88));
        TabaixopesoBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TabaixopesoBTN.setText("Ver treinos");
        TabaixopesoBTN.setFocusPainted(false);
        TabaixopesoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabaixopesoBTNActionPerformed(evt);
            }
        });
        jPanel3.add(TabaixopesoBTN);
        TabaixopesoBTN.setBounds(150, 150, 150, 60);

        TnormalBTN.setBackground(new java.awt.Color(48, 165, 88));
        TnormalBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TnormalBTN.setText("Ver treinos");
        TnormalBTN.setFocusPainted(false);
        TnormalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TnormalBTNActionPerformed(evt);
            }
        });
        jPanel3.add(TnormalBTN);
        TnormalBTN.setBounds(570, 150, 150, 60);

        TacimapesoBTN.setBackground(new java.awt.Color(48, 165, 88));
        TacimapesoBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TacimapesoBTN.setText("Ver treinos");
        TacimapesoBTN.setFocusPainted(false);
        TacimapesoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TacimapesoBTNActionPerformed(evt);
            }
        });
        jPanel3.add(TacimapesoBTN);
        TacimapesoBTN.setBounds(150, 470, 150, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Em caso de alteração na prática e tipo de treino consulte um médico ou especialista.");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(190, 280, 520, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("ATENÇÃO: Utilize os treinos que condizem com seus status de saúde.");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(230, 260, 430, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuBTNActionPerformed
        // TODO add your handling code here:
        new MainMenu(this.user).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackToMenuBTNActionPerformed

    private void TobsesoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TobsesoBTNActionPerformed
        // TODO add your handling code here:
        new TrainingsObesidade(this.user).setVisible(true);
    }//GEN-LAST:event_TobsesoBTNActionPerformed

    private void TabaixopesoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabaixopesoBTNActionPerformed
        // TODO add your handling code here:
        new TrainingAbaixoPeso(this.user).setVisible(true);
    }//GEN-LAST:event_TabaixopesoBTNActionPerformed

    private void TnormalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TnormalBTNActionPerformed
        // TODO add your handling code here:
        new TrainingsNormal(this.user).setVisible(true);
    }//GEN-LAST:event_TnormalBTNActionPerformed

    private void TacimapesoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TacimapesoBTNActionPerformed
        // TODO add your handling code here:
        new TrainingsAcimaPeso(this.user).setVisible(true);
    }//GEN-LAST:event_TacimapesoBTNActionPerformed

    private void windowOnClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowOnClose
        new MainMenu(this.user).setVisible(true);
    }//GEN-LAST:event_windowOnClose

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trainings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trainings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trainings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trainings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trainings(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenuBTN;
    private javax.swing.JButton TabaixopesoBTN;
    private javax.swing.JButton TacimapesoBTN;
    private javax.swing.JButton TnormalBTN;
    private javax.swing.JButton TobsesoBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
